"""Rigid/Jolt 持久 RNA 的纯数据 schema；不导入 bpy。"""

RIGID_BODY_RNA_FIELDS = ({'name': 'enabled', 'property': 'bool', 'kwargs': {'name': '启用', 'description': '将此对象纳入刚体模拟', 'default': False}},
 {'name': 'body_type',
  'property': 'enum',
  'kwargs': {'name': '刚体类型',
             'description': '刚体的运动学类型',
             'items': [('DYNAMIC', '动态', '受重力和碰撞力驱动；需要设置质量'),
                       ('STATIC', '静态', '固定不动的碰撞体；不响应外力'),
                       ('KINEMATIC', '运动学', '由动画/节点驱动位移，不受物理力影响但会推动其他刚体')],
             'default': 'DYNAMIC'}},
 {'name': 'mass',
  'property': 'float',
  'kwargs': {'name': '质量',
             'description': '动态刚体的质量（千克）；静态和运动学类型忽略此值',
             'default': 1.0,
             'min': 0.001,
             'soft_max': 1000.0}},
 {'name': 'friction',
  'property': 'float',
  'kwargs': {'name': '摩擦', 'description': '碰撞面摩擦系数；0=无摩擦，1=最大摩擦', 'default': 0.5, 'min': 0.0, 'max': 1.0}},
 {'name': 'restitution',
  'property': 'float',
  'kwargs': {'name': '弹性', 'description': '碰撞弹性系数（恢复系数）；0=完全非弹性，1=完全弹性', 'default': 0.0, 'min': 0.0, 'max': 1.0}},
 {'name': 'rigid_collision_group',
  'property': 'int',
  'kwargs': {'name': '刚体碰撞组', 'description': '刚体所属过滤组，仅在刚体/Jolt 求解器内部使用（1..16）', 'default': 1, 'min': 1, 'max': 16}},
 {'name': 'rigid_collides_with_groups',
  'property': 'int',
  'kwargs': {'name': '可碰刚体组',
             'description': '允许哪些刚体碰撞组与此刚体碰撞；两个刚体需互相允许才会碰撞',
             'default': 65535,
             'min': 0,
             'max': 65535}},
 {'name': 'shape_type',
  'property': 'enum',
  'kwargs': {'name': '形状',
             'description': '刚体碰撞形状类型',
             'items': [('SPHERE', '球体', '球形；由半径决定大小'),
                       ('CAPSULE', '胶囊', '胶囊；由半径和高度决定大小'),
                       ('CYLINDER', '圆柱', '圆柱；局部Y轴为高度方向'),
                       ('TAPERED_CAPSULE', '锥形胶囊', '两端半径可不同的胶囊；局部Y轴为高度方向'),
                       ('TAPERED_CYLINDER', '锥形圆柱', '两端半径可不同的圆柱；局部Y轴为高度方向'),
                       ('PLANE', '平面', '无限静态平面；局部XY为平面，局部Z为法线'),
                       ('BOX', '长方体', '轴对齐长方体；由三轴半尺寸决定大小'),
                       ('MESH', '网格', '使用对象网格；动态/运动学物体在 Jolt 中使用同几何凸包')],
             'default': 'SPHERE'}},
 {'name': 'shape_radius',
  'property': 'float',
  'kwargs': {'name': '半径',
             'description': '球体半径，或胶囊/圆柱截面半径',
             'default': 0.5,
             'min': 0.001,
             'soft_max': 10.0,
             'unit': 'LENGTH'}},
 {'name': 'shape_half_height',
  'property': 'float',
  'kwargs': {'name': '半高',
             'description': '沿局部Y轴的半长；胶囊总高度 = 半高×2 + 半径×2',
             'default': 0.5,
             'min': 0.001,
             'soft_max': 10.0,
             'unit': 'LENGTH'}},
 {'name': 'shape_half_extents',
  'property': 'float_vector',
  'kwargs': {'name': '半尺寸',
             'description': '长方体在 X/Y/Z 轴的半尺寸（BOX）',
             'default': (0.5, 0.5, 0.5),
             'min': 0.001,
             'soft_max': 10.0,
             'size': 3,
             'unit': 'LENGTH',
             'subtype': 'XYZ'}},
 {'name': 'shape_plane_half_extent',
  'property': 'float',
  'kwargs': {'name': '平面范围',
             'description': 'Jolt PlaneShape broadphase/debug 半范围；物理平面本身无厚度',
             'default': 10.0,
             'min': 1.0,
             'soft_max': 1000.0,
             'unit': 'LENGTH'}},
 {'name': 'shape_top_radius',
  'property': 'float',
  'kwargs': {'name': '顶部半径',
             'description': '锥形胶囊/锥形圆柱在局部 +Y 端的半径',
             'default': 0.5,
             'min': 0.001,
             'soft_max': 10.0,
             'unit': 'LENGTH'}},
 {'name': 'shape_bottom_radius',
  'property': 'float',
  'kwargs': {'name': '底部半径',
             'description': '锥形胶囊/锥形圆柱在局部 -Y 端的半径',
             'default': 0.3,
             'min': 0.001,
             'soft_max': 10.0,
             'unit': 'LENGTH'}},
 {'name': 'shape_convex_radius',
  'property': 'float',
  'kwargs': {'name': '凸半径',
             'description': 'Jolt convex radius；用于圆柱/锥形圆柱边缘圆角和接触稳定性',
             'default': 0.05,
             'min': 0.0,
             'soft_max': 1.0,
             'unit': 'LENGTH'}},
 {'name': 'shape_offset',
  'property': 'float_vector',
  'kwargs': {'name': '局部偏移',
             'description': '碰撞形状相对Object原点的局部偏移',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'unit': 'LENGTH',
             'subtype': 'XYZ'}},
 {'name': 'shape_rotation',
  'property': 'float_vector',
  'kwargs': {'name': '局部旋转',
             'description': '碰撞形状相对Object旋转的局部欧拉旋转',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'unit': 'ROTATION',
             'subtype': 'EULER'}},
 {'name': 'linear_velocity',
  'property': 'float_vector',
  'kwargs': {'name': '线速度',
             'description': '动态刚体注册到Jolt时的初始世界线速度',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'subtype': 'XYZ'}},
 {'name': 'angular_velocity',
  'property': 'float_vector',
  'kwargs': {'name': '角速度',
             'description': '动态刚体注册到Jolt时的初始世界角速度（rad/s）',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'subtype': 'XYZ'}},
 {'name': 'linear_damping',
  'property': 'float',
  'kwargs': {'name': '线阻尼', 'description': '线速度阻尼；Jolt建议范围0..1，通常接近0', 'default': 0.05, 'min': 0.0, 'max': 1.0}},
 {'name': 'angular_damping',
  'property': 'float',
  'kwargs': {'name': '角阻尼', 'description': '角速度阻尼；Jolt建议范围0..1，通常接近0', 'default': 0.05, 'min': 0.0, 'max': 1.0}},
 {'name': 'gravity_factor',
  'property': 'float',
  'kwargs': {'name': '重力倍率', 'description': '该刚体受到的世界重力倍率；0表示不受重力', 'default': 1.0, 'soft_min': 0.0, 'soft_max': 2.0}},
 {'name': 'allow_sleeping',
  'property': 'bool',
  'kwargs': {'name': '允许睡眠', 'description': '允许Jolt在刚体静止后让它进入睡眠以节省计算', 'default': True}},
 {'name': 'start_deactivated',
  'property': 'bool',
  'kwargs': {'name': '初始停用',
             'description': '动态刚体以非激活状态加入Jolt；接触或显式激活前不受重力推进',
             'default': False}},
 {'name': 'motion_quality',
  'property': 'enum',
  'kwargs': {'name': '碰撞质量',
             'description': '高速刚体的碰撞检测质量',
             'items': [('DISCRETE', '离散', '普通离散步进，速度过高时可能穿透薄物体'), ('LINEAR_CAST', 'CCD', '使用线性投射降低高速穿透风险，成本更高')],
             'default': 'DISCRETE'}},
 {'name': 'max_linear_velocity',
  'property': 'float',
  'kwargs': {'name': '最大线速度', 'description': 'Jolt允许该刚体达到的最大线速度', 'default': 500.0, 'min': 0.0, 'soft_max': 500.0}},
 {'name': 'max_angular_velocity',
  'property': 'float',
  'kwargs': {'name': '最大角速度',
             'description': 'Jolt允许该刚体达到的最大角速度（rad/s）',
             'default': 47.1239,
             'min': 0.0,
             'soft_max': 100.0}},
 {'name': 'is_sensor',
  'property': 'bool',
  'kwargs': {'name': '传感器', 'description': '作为触发体接收接触事件，但不产生碰撞响应；事件输出接入前仅作为Jolt body设置', 'default': False}},
 {'name': 'collide_kinematic_vs_non_dynamic',
  'property': 'bool',
  'kwargs': {'name': '运动学碰静态', 'description': '允许运动学体和静态/运动学体生成接触点；大型传感器会显著增加接触成本', 'default': False}},
 {'name': 'lock_linear_x', 'property': 'bool', 'kwargs': {'name': '锁定线性X', 'default': False}},
 {'name': 'lock_linear_y', 'property': 'bool', 'kwargs': {'name': '锁定线性Y', 'default': False}},
 {'name': 'lock_linear_z', 'property': 'bool', 'kwargs': {'name': '锁定线性Z', 'default': False}},
 {'name': 'lock_angular_x', 'property': 'bool', 'kwargs': {'name': '锁定角度X', 'default': False}},
 {'name': 'lock_angular_y', 'property': 'bool', 'kwargs': {'name': '锁定角度Y', 'default': False}},
 {'name': 'lock_angular_z', 'property': 'bool', 'kwargs': {'name': '锁定角度Z', 'default': False}})


def _six_dof_axis_rna_fields() -> tuple[dict, ...]:
    """生成 SixDOF 六轴属性，保持字段命名与 native 轴序一致。"""
    definitions = (
        ("translation_x", "平移X", "LENGTH", -1.0, 1.0),
        ("translation_y", "平移Y", "LENGTH", -1.0, 1.0),
        ("translation_z", "平移Z", "LENGTH", -1.0, 1.0),
        ("rotation_x", "旋转X", "ROTATION", -0.7853981633974483, 0.7853981633974483),
        ("rotation_y", "旋转Y", "ROTATION", -0.7853981633974483, 0.7853981633974483),
        ("rotation_z", "旋转Z", "ROTATION", -0.7853981633974483, 0.7853981633974483),
    )
    fields = []
    for axis_name, label, unit, default_min, default_max in definitions:
        fields.append({
            "name": f"six_dof_{axis_name}_mode",
            "property": "enum",
            "kwargs": {
                "name": f"{label}模式",
                "description": f"SixDOF {label}轴是自由、固定到零位还是限制在范围内",
                "items": [
                    ("FREE", "自由", "该轴不施加约束"),
                    ("FIXED", "固定", "该轴固定在约束frame零位"),
                    ("LIMITED", "限制", "该轴限制在最小值和最大值之间"),
                ],
                "default": "FIXED",
            },
        })
        for suffix, suffix_label, default in (
            ("min", "最小", default_min), ("max", "最大", default_max),
        ):
            kwargs = {
                "name": f"{label}{suffix_label}",
                "description": f"SixDOF {label}轴限制的{suffix_label}值",
                "default": default,
                "unit": unit,
            }
            if unit == "ROTATION":
                kwargs.update({"min": -3.141592653589793, "max": 3.141592653589793})
            fields.append({
                "name": f"six_dof_{axis_name}_{suffix}",
                "property": "float",
                "kwargs": kwargs,
            })
        if axis_name.startswith("translation"):
            fields.extend((
                {
                    "name": f"six_dof_{axis_name}_limit_spring_frequency",
                    "property": "float",
                    "kwargs": {
                        "name": f"{label}限制弹簧频率",
                        "description": f"SixDOF {label}软限制的频率；0表示硬限制",
                        "default": 0.0,
                        "min": 0.0,
                        "soft_max": 20.0,
                    },
                },
                {
                    "name": f"six_dof_{axis_name}_limit_spring_damping",
                    "property": "float",
                    "kwargs": {
                        "name": f"{label}限制弹簧阻尼",
                        "description": f"SixDOF {label}软限制的阻尼比",
                        "default": 0.0,
                        "min": 0.0,
                        "soft_max": 2.0,
                    },
                },
            ))
        friction_kind = "摩擦力" if axis_name.startswith("translation") else "摩擦力矩"
        fields.append({
            "name": f"six_dof_{axis_name}_friction",
            "property": "float",
            "kwargs": {
                "name": f"{label}{friction_kind}",
                "description": f"SixDOF {label}轴的最大{friction_kind}；0表示无摩擦",
                "default": 0.0,
                "min": 0.0,
                "soft_max": 1000.0,
            },
        })
        fields.append({
            "name": f"six_dof_{axis_name}_motor_state",
            "property": "enum",
            "kwargs": {
                "name": f"{label} Motor",
                "description": f"SixDOF {label}轴的 Motor 驱动模式",
                "items": [
                    ("OFF", "关闭", "不驱动该轴"),
                    ("VELOCITY", "速度", "驱动该轴达到目标速度"),
                    ("POSITION", "位置", "驱动该轴达到目标位置或姿态"),
                ],
                "default": "OFF",
            },
        })
    return tuple(fields)


RIGID_CONSTRAINT_RNA_FIELDS = ({'name': 'enabled',
  'property': 'bool',
  'kwargs': {'name': '启用', 'description': '将此 Empty 对象识别为刚体约束点', 'default': False}},
 {'name': 'constraint_type',
  'property': 'enum',
  'kwargs': {'name': '约束类型',
             'description': '约束的自由度限制方式',
             'items': [('FIXED', '固定', '完全锁定两个刚体之间的相对运动'),
                       ('HINGE', '铰链', '绕约束锚点 Z 轴允许旋转，限制其余自由度'),
                       ('SLIDER', '滑动', '允许沿约束锚点 Z 轴平移，限制旋转'),
                       ('CONE', '锥形', '允许在锥角范围内摆动，限制平移'),
                       ('SWING_TWIST', '摆动扭转', '肩关节式限制摆动锥和绕局部Z轴的扭转范围'),
                       ('SIX_DOF', '六自由度', '分别配置三个平移轴和三个旋转轴为自由、固定或受限'),
                       ('PULLEY', '滑轮', '两个刚体连接点经两个世界固定点保持加权绳长'),
                       ('GEAR', '齿轮', '引用两个铰链并约束两刚体绕各自轴的旋转比例'),
                       ('RACK_AND_PINION', '齿条齿轮', '引用铰链和滑动约束并耦合旋转与直线位移'),
                       ('POINT', '点约束', '仅锁定位置，允许任意旋转（球窝关节）'),
                       ('DISTANCE', '距离', '限制两个锚点之间的最小和最大距离')],
             'default': 'FIXED'}},
 {'name': 'target_a',
  'property': 'pointer',
  'kwargs': {'type': 'Object', 'name': '刚体 A', 'description': '约束的第一个刚体目标；留空表示约束到世界原点'}},
 {'name': 'target_b',
  'property': 'pointer',
  'kwargs': {'type': 'Object', 'name': '刚体 B', 'description': '约束的第二个刚体目标；留空表示约束到世界原点'}},
 {'name': 'reference_constraint_a',
  'property': 'pointer',
  'kwargs': {'type': 'Object', 'name': '引用约束 A', 'description': 'Gear 需要 Hinge；RackAndPinion 需要 pinion 的 Hinge'}},
 {'name': 'reference_constraint_b',
  'property': 'pointer',
  'kwargs': {'type': 'Object', 'name': '引用约束 B', 'description': 'Gear 需要 Hinge；RackAndPinion 需要 rack 的 Slider'}},
 {'name': 'anchor_mode',
  'property': 'enum',
  'kwargs': {'name': '锚点模式',
             'description': '使用Empty共享世界锚点，或分别使用刚体A/B局部空间中的锚点frame',
             'items': [('SHARED_WORLD', '共享世界锚点', '两个刚体使用当前Empty的世界位置和旋转'),
                       ('LOCAL_FRAMES', '独立局部Frame', '分别从刚体A/B局部点和局部旋转构造世界锚点frame')],
             'default': 'SHARED_WORLD'}},
 {'name': 'local_point_a',
  'property': 'float_vector',
  'kwargs': {'name': 'A局部锚点',
             'description': '锚点相对刚体A Object局部空间的位置；A为空时按世界坐标解释',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'unit': 'LENGTH',
             'subtype': 'XYZ'}},
 {'name': 'local_rotation_a',
  'property': 'float_vector',
  'kwargs': {'name': 'A局部旋转',
             'description': '锚点frame相对刚体A Object局部空间的欧拉旋转',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'unit': 'ROTATION',
             'subtype': 'EULER'}},
 {'name': 'local_point_b',
  'property': 'float_vector',
  'kwargs': {'name': 'B局部锚点',
             'description': '锚点相对刚体B Object局部空间的位置；B为空时按世界坐标解释',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'unit': 'LENGTH',
             'subtype': 'XYZ'}},
 {'name': 'local_rotation_b',
  'property': 'float_vector',
  'kwargs': {'name': 'B局部旋转',
             'description': '锚点frame相对刚体B Object局部空间的欧拉旋转',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'unit': 'ROTATION',
             'subtype': 'EULER'}},
 {'name': 'disable_collisions',
  'property': 'bool',
  'kwargs': {'name': '禁用连接体碰撞', 'description': '约束连接的两个刚体不再彼此碰撞；不影响它们与其他刚体的碰撞', 'default': True}},
 {'name': 'breakable',
  'property': 'bool',
  'kwargs': {'name': '可断裂', 'description': '当上一物理步的约束冲量超过阈值时禁用此约束', 'default': False}},
 {'name': 'breaking_threshold',
  'property': 'float',
  'kwargs': {'name': '断裂冲量阈值',
             'description': '约束断裂阈值，单位是Jolt每个物理步累计的lambda/冲量，不是力',
             'default': 1000.0,
             'min': 0.0,
             'soft_max': 10000.0}},
 {'name': 'constraint_priority',
  'property': 'int',
  'kwargs': {'name': '求解优先级', 'description': 'Jolt约束求解优先级；更高数值会更优先满足', 'default': 0, 'min': 0}},
 {'name': 'solver_velocity_steps',
  'property': 'int',
  'kwargs': {'name': '速度迭代覆盖',
             'description': '0表示使用物理世界默认速度迭代次数；非0会覆盖该约束所在岛的速度迭代下限',
             'default': 0,
             'min': 0,
             'max': 255}},
 {'name': 'solver_position_steps',
  'property': 'int',
  'kwargs': {'name': '位置迭代覆盖',
             'description': '0表示使用物理世界默认位置迭代次数；非0会覆盖该约束所在岛的位置迭代下限',
             'default': 0,
             'min': 0,
             'max': 255}},
 {'name': 'draw_constraint_size',
  'property': 'float',
  'kwargs': {'name': '调试显示尺寸',
             'description': 'Jolt debug renderer使用的约束显示尺寸；当前先作为调试可视化数据保留',
             'default': 1.0,
             'min': 0.0,
             'soft_max': 10.0}},
 {'name': 'limit_enabled',
  'property': 'bool',
  'kwargs': {'name': '启用限制', 'description': '为Hinge启用角度限制，或为Slider启用线性行程限制', 'default': False}},
 {'name': 'angular_limit_min',
  'property': 'float',
  'kwargs': {'name': '最小角度',
             'description': 'Hinge最小旋转角度；范围[-π, 0]',
             'default': -3.141592653589793,
             'min': -3.141592653589793,
             'max': 0.0,
             'unit': 'ROTATION'}},
 {'name': 'angular_limit_max',
  'property': 'float',
  'kwargs': {'name': '最大角度',
             'description': 'Hinge最大旋转角度；范围[0, π]',
             'default': 3.141592653589793,
             'min': 0.0,
             'max': 3.141592653589793,
             'unit': 'ROTATION'}},
 {'name': 'linear_limit_min',
  'property': 'float',
  'kwargs': {'name': '最小行程', 'description': 'Slider沿约束轴的最小位移', 'default': -1.0, 'unit': 'LENGTH'}},
 {'name': 'linear_limit_max',
  'property': 'float',
  'kwargs': {'name': '最大行程', 'description': 'Slider沿约束轴的最大位移', 'default': 1.0, 'unit': 'LENGTH'}},
 {'name': 'limit_spring_frequency',
  'property': 'float',
  'kwargs': {'name': '限制弹簧频率', 'description': '大于0时将硬限制变为软限制；单位Hz', 'default': 0.0, 'min': 0.0, 'soft_max': 20.0}},
 {'name': 'limit_spring_damping',
  'property': 'float',
  'kwargs': {'name': '限制弹簧阻尼', 'description': '限制弹簧阻尼比；0无阻尼，1约等于临界阻尼', 'default': 0.0, 'min': 0.0, 'soft_max': 2.0}},
 {'name': 'max_friction_torque',
  'property': 'float',
  'kwargs': {'name': '最大摩擦扭矩',
             'description': 'Hinge或SwingTwist未启用motor时用于阻碍旋转的最大摩擦扭矩',
             'default': 0.0,
             'min': 0.0,
             'soft_max': 1000.0}},
 {'name': 'max_friction_force',
  'property': 'float',
  'kwargs': {'name': '最大摩擦力',
             'description': 'Slider未启用motor时用于阻碍滑动的最大摩擦力',
             'default': 0.0,
             'min': 0.0,
             'soft_max': 1000.0}},
 {'name': 'motor_state',
  'property': 'enum',
  'kwargs': {'name': 'Motor',
             'description': 'Hinge或Slider motor状态',
             'items': [('OFF', '关闭', '不驱动约束'), ('VELOCITY', '速度', '驱动到目标速度'), ('POSITION', '位置', '驱动到目标位置/角度')],
             'default': 'OFF'}},
 {'name': 'motor_frequency',
  'property': 'float',
  'kwargs': {'name': 'Motor频率', 'description': 'Motor位置弹簧频率；单位Hz', 'default': 2.0, 'min': 0.0, 'soft_max': 20.0}},
 {'name': 'motor_damping',
  'property': 'float',
  'kwargs': {'name': 'Motor阻尼', 'description': 'Motor位置弹簧阻尼比', 'default': 1.0, 'min': 0.0, 'soft_max': 2.0}},
 {'name': 'motor_force_limit',
  'property': 'float',
  'kwargs': {'name': 'Motor力限制',
             'description': 'Slider motor最大力；0表示使用Jolt默认无限制',
             'default': 0.0,
             'min': 0.0,
             'soft_max': 1000.0}},
 {'name': 'motor_torque_limit',
  'property': 'float',
  'kwargs': {'name': 'Motor扭矩限制',
             'description': 'Hinge或SwingTwist motor最大扭矩；0表示使用Jolt默认无限制',
             'default': 0.0,
             'min': 0.0,
             'soft_max': 1000.0}},
 {'name': 'motor_target_angular_velocity',
  'property': 'float',
  'kwargs': {'name': '目标角速度', 'description': 'Hinge速度motor目标角速度（rad/s）', 'default': 0.0}},
 {'name': 'motor_target_angle',
  'property': 'float',
  'kwargs': {'name': '目标角度', 'description': 'Hinge位置motor目标角度', 'default': 0.0, 'unit': 'ROTATION'}},
 {'name': 'motor_target_velocity',
  'property': 'float',
  'kwargs': {'name': '目标线速度', 'description': 'Slider速度motor目标线速度', 'default': 0.0}},
 {'name': 'motor_target_position',
  'property': 'float',
  'kwargs': {'name': '目标位置', 'description': 'Slider位置motor目标位移', 'default': 0.0, 'unit': 'LENGTH'}},
 {'name': 'swing_motor_state',
  'property': 'enum',
  'kwargs': {'name': '摆动Motor',
             'description': 'SwingTwist摆动平面的motor状态',
             'items': [('OFF', '关闭', '不驱动摆动'), ('VELOCITY', '速度', '驱动摆动角速度'), ('POSITION', '姿态', '驱动到目标姿态的摆动部分')],
             'default': 'OFF'}},
 {'name': 'twist_motor_state',
  'property': 'enum',
  'kwargs': {'name': '扭转Motor',
             'description': 'SwingTwist绕局部Z轴的motor状态',
             'items': [('OFF', '关闭', '不驱动扭转'), ('VELOCITY', '速度', '驱动扭转角速度'), ('POSITION', '姿态', '驱动到目标姿态的扭转部分')],
             'default': 'OFF'}},
 {'name': 'swing_twist_target_angular_velocity',
  'property': 'float_vector',
  'kwargs': {'name': '摆动扭转目标角速度',
             'description': 'SwingTwist在HoTools约束frame局部XYZ中的目标角速度，单位rad/s；Z为twist轴',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'subtype': 'XYZ'}},
 {'name': 'swing_twist_target_rotation',
  'property': 'float_vector',
  'kwargs': {'name': '摆动扭转目标姿态',
             'description': 'SwingTwist位置motor在HoTools约束frame中的目标欧拉姿态',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'unit': 'ROTATION',
             'subtype': 'EULER'}},
 {'name': 'six_dof_swing_type',
  'property': 'enum',
  'kwargs': {'name': 'SixDOF摆动边界',
             'description': '旋转Y/Z同时受限时使用椭圆锥或金字塔边界',
             'items': [('CONE', '椭圆锥', '旋转Y/Z组成对称椭圆锥'),
                       ('PYRAMID', '角锥', '旋转Y/Z分别使用独立范围')],
             'default': 'PYRAMID'}},
 *_six_dof_axis_rna_fields(),
 {'name': 'six_dof_target_velocity',
  'property': 'float_vector',
  'kwargs': {'name': 'SixDOF目标线速度',
             'description': 'SixDOF速度Motor在约束frame局部XYZ中的目标线速度',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'subtype': 'XYZ'}},
 {'name': 'six_dof_target_angular_velocity',
  'property': 'float_vector',
  'kwargs': {'name': 'SixDOF目标角速度',
             'description': 'SixDOF速度Motor在约束frame局部XYZ中的目标角速度，单位rad/s',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'subtype': 'XYZ'}},
 {'name': 'six_dof_target_position',
  'property': 'float_vector',
  'kwargs': {'name': 'SixDOF目标位置',
             'description': 'SixDOF位置Motor在约束frame局部XYZ中的目标平移',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'unit': 'LENGTH',
             'subtype': 'XYZ'}},
 {'name': 'six_dof_target_rotation',
  'property': 'float_vector',
  'kwargs': {'name': 'SixDOF目标姿态',
             'description': 'SixDOF位置Motor在约束frame中的目标欧拉姿态',
             'default': (0.0, 0.0, 0.0),
             'size': 3,
             'unit': 'ROTATION',
             'subtype': 'EULER'}},
 {'name': 'cone_half_angle',
  'property': 'float',
  'kwargs': {'name': '半锥角',
             'description': 'Cone约束允许的最大摆动半角；0保持旧行为',
             'default': 0.0,
             'min': 0.0,
             'max': 3.141592653589793,
             'unit': 'ROTATION'}},
 {'name': 'swing_type',
  'property': 'enum',
  'kwargs': {'name': '摆动边界',
             'description': 'Cone使用椭圆锥边界，Pyramid使用独立平面角边界',
             'items': [('CONE', '椭圆锥', '连续椭圆摆动边界'),
                       ('PYRAMID', '角锥', '两个摆动平面分别限幅')],
             'default': 'CONE'}},
 {'name': 'swing_normal_half_angle',
  'property': 'float',
  'kwargs': {'name': '法向摆动半角', 'default': 0.7853981633974483, 'min': 0.0, 'max': 3.141592653589793, 'unit': 'ROTATION'}},
 {'name': 'swing_plane_half_angle',
  'property': 'float',
  'kwargs': {'name': '平面摆动半角', 'default': 0.7853981633974483, 'min': 0.0, 'max': 3.141592653589793, 'unit': 'ROTATION'}},
 {'name': 'twist_min_angle',
  'property': 'float',
  'kwargs': {'name': '最小扭转角', 'default': -0.7853981633974483, 'min': -3.141592653589793, 'max': 3.141592653589793, 'unit': 'ROTATION'}},
 {'name': 'twist_max_angle',
  'property': 'float',
  'kwargs': {'name': '最大扭转角', 'default': 0.7853981633974483, 'min': -3.141592653589793, 'max': 3.141592653589793, 'unit': 'ROTATION'}},
 {'name': 'distance_min',
  'property': 'float',
  'kwargs': {'name': '最小距离', 'description': 'Distance约束允许两个锚点保持的最小距离', 'default': 0.0, 'min': 0.0, 'unit': 'LENGTH'}},
 {'name': 'distance_max',
  'property': 'float',
  'kwargs': {'name': '最大距离', 'description': 'Distance约束允许两个锚点保持的最大距离', 'default': 1.0, 'min': 0.0, 'unit': 'LENGTH'}},
 {'name': 'pulley_fixed_point_a',
  'property': 'float_vector',
  'kwargs': {'name': '滑轮固定点A', 'description': '连接刚体A绳段的世界空间固定点', 'default': (-1.0, 2.0, 0.0), 'size': 3, 'unit': 'LENGTH', 'subtype': 'XYZ'}},
 {'name': 'pulley_fixed_point_b',
  'property': 'float_vector',
  'kwargs': {'name': '滑轮固定点B', 'description': '连接刚体B绳段的世界空间固定点', 'default': (1.0, 2.0, 0.0), 'size': 3, 'unit': 'LENGTH', 'subtype': 'XYZ'}},
 {'name': 'pulley_ratio',
  'property': 'float',
  'kwargs': {'name': '滑轮倍率', 'description': '加权绳长公式中第二段绳长的倍率', 'default': 1.0, 'min': 0.0001, 'soft_max': 10.0}},
 {'name': 'pulley_min_length',
  'property': 'float',
  'kwargs': {'name': '滑轮最小绳长', 'description': '-1表示按创建时加权绳长自动计算', 'default': 0.0, 'min': -1.0, 'unit': 'LENGTH'}},
 {'name': 'pulley_max_length',
  'property': 'float',
  'kwargs': {'name': '滑轮最大绳长', 'description': '-1表示按创建时加权绳长自动计算', 'default': -1.0, 'min': -1.0, 'unit': 'LENGTH'}},
 {'name': 'gear_ratio',
  'property': 'float',
  'kwargs': {'name': '齿轮比', 'description': 'Gear1Rotation = -ratio * Gear2Rotation', 'default': 1.0, 'min': 0.0001, 'soft_max': 100.0}},
 {'name': 'rack_and_pinion_ratio',
  'property': 'float',
  'kwargs': {'name': '齿条齿轮比', 'description': 'PinionRotation = ratio * RackTranslation，单位为弧度/米', 'default': 1.0, 'min': 0.0001, 'soft_max': 100.0}})


RIGID_RNA_SCHEMAS = {
    "rigid_body": RIGID_BODY_RNA_FIELDS,
    "rigid_constraint": RIGID_CONSTRAINT_RNA_FIELDS,
}


__all__ = [
    "RIGID_BODY_RNA_FIELDS",
    "RIGID_CONSTRAINT_RNA_FIELDS",
    "RIGID_RNA_SCHEMAS",
]
