"""Physics World Field 领域的公共标识符。"""

FIELD_ABI_VERSION = 0
FIELD_OBJECT_TAG = "physics.field"
FIELD_SNAPSHOT_CACHE_KEY_V0 = "field_snapshot_v0"
FIELD_NATIVE_RUNTIME_CACHE_KEY_V1 = "field_native_runtime_v1"
FIELD_COMPONENT_ID = "field"
FIELD_CAPABILITY_ID = "field_air_velocity"

AIR_VELOCITY_CHANNEL_ID = "air_velocity"
WIND_GENERATOR_ID = "analytic.wind.v0"

FIELD_STATUS_ACTIVE = "ACTIVE"
FIELD_STATUS_PREVIEW_ONLY = "PREVIEW_ONLY"
FIELD_STATUS_RESERVED = "RESERVED"
FIELD_STATUS_INVALID = "INVALID"
FIELD_STATUSES = (
    FIELD_STATUS_ACTIVE,
    FIELD_STATUS_PREVIEW_ONLY,
    FIELD_STATUS_RESERVED,
    FIELD_STATUS_INVALID,
)

# Field 类型先于具体 generator 参数存在；Wind 是 V0 唯一落地类型。
FIELD_TYPE_WIND = "WIND"
FIELD_TYPES_V0 = (FIELD_TYPE_WIND,)

VOLUME_SHAPE_SPHERE = "SPHERE"
VOLUME_SHAPE_BOX = "BOX"
VOLUME_SHAPES_V0 = (VOLUME_SHAPE_SPHERE, VOLUME_SHAPE_BOX)

SPHERE_ATTENUATION_POLICY_V0 = "sphere_linear_v0"
BOX_ATTENUATION_POLICY_V0 = "box_none_v0"
VOLUME_ATTENUATION_POLICY_VERSION = 0

WIND_NOISE_ALGORITHM_VERSION = 0

FIELD_DIAGNOSTICS_CHANNEL = "physics.field.diagnostics"
FIELD_STATS_CHANNEL = "physics.field.stats"

FIELD_UNSUPPORTED_CHANNEL = "FIELD_UNSUPPORTED_CHANNEL"
FIELD_UNSUPPORTED_SOURCE = "FIELD_UNSUPPORTED_SOURCE"
FIELD_UNSUPPORTED_SAMPLE_MODE = "FIELD_UNSUPPORTED_SAMPLE_MODE"
FIELD_OUT_OF_SCOPE = "FIELD_OUT_OF_SCOPE"
FIELD_INVALID_SPEC = "FIELD_INVALID_SPEC"
FIELD_PREVIEW_ONLY = "FIELD_PREVIEW_ONLY"
FIELD_RESERVED_CHANNEL = "FIELD_RESERVED_CHANNEL"
FIELD_MATRIX_VISUALIZATION_RESERVED = "FIELD_MATRIX_VISUALIZATION_RESERVED"
FIELD_CONSUMER_NOT_REGISTERED = "FIELD_CONSUMER_NOT_REGISTERED"
FIELD_VOLUME_NON_UNIFORM_SPHERE = "FIELD_VOLUME_NON_UNIFORM_SPHERE"
FIELD_ATTENUATION_POLICY_UNSUPPORTED = "FIELD_ATTENUATION_POLICY_UNSUPPORTED"


__all__ = [
    "AIR_VELOCITY_CHANNEL_ID",
    "BOX_ATTENUATION_POLICY_V0",
    "FIELD_ABI_VERSION",
    "FIELD_ATTENUATION_POLICY_UNSUPPORTED",
    "FIELD_CAPABILITY_ID",
    "FIELD_COMPONENT_ID",
    "FIELD_CONSUMER_NOT_REGISTERED",
    "FIELD_DIAGNOSTICS_CHANNEL",
    "FIELD_INVALID_SPEC",
    "FIELD_MATRIX_VISUALIZATION_RESERVED",
    "FIELD_NATIVE_RUNTIME_CACHE_KEY_V1",
    "FIELD_OBJECT_TAG",
    "FIELD_SNAPSHOT_CACHE_KEY_V0",
    "FIELD_OUT_OF_SCOPE",
    "FIELD_PREVIEW_ONLY",
    "FIELD_RESERVED_CHANNEL",
    "FIELD_STATS_CHANNEL",
    "FIELD_STATUSES",
    "FIELD_STATUS_ACTIVE",
    "FIELD_STATUS_INVALID",
    "FIELD_STATUS_PREVIEW_ONLY",
    "FIELD_STATUS_RESERVED",
    "FIELD_TYPE_WIND",
    "FIELD_TYPES_V0",
    "FIELD_UNSUPPORTED_CHANNEL",
    "FIELD_UNSUPPORTED_SAMPLE_MODE",
    "FIELD_UNSUPPORTED_SOURCE",
    "FIELD_VOLUME_NON_UNIFORM_SPHERE",
    "SPHERE_ATTENUATION_POLICY_V0",
    "VOLUME_ATTENUATION_POLICY_VERSION",
    "VOLUME_SHAPES_V0",
    "VOLUME_SHAPE_BOX",
    "VOLUME_SHAPE_SPHERE",
    "WIND_GENERATOR_ID",
    "WIND_NOISE_ALGORITHM_VERSION",
]
